### ISSUE TITLE
Go get doesn't work due to change of version for backoff ?

### ISSUE THREAD

**Issue by lmaitresym** [andresvia/go-awsecs#11]
Hi,

I am a beginner in go and when i try to checkout this project i have the following error:

```sh
$ go get github.com/Autodesk/go-awsecs
package github.com/cenkalti/backoff/v3: cannot find package "github.com/cenkalti/backoff/v3" in any of:
	/usr/local/go/src/github.com/cenkalti/backoff/v3 (from $GOROOT)
	/Users/ludovic.maitre/go/src/github.com/cenkalti/backoff/v3 (from $GOPATH)
```

Patching the `go.mod` file to use backoff v4 looks to work:
```sh
$ git diff go.mod 
diff --git a/go.mod b/go.mod
index 56be22b..3f30cb6 100644
--- a/go.mod
+++ b/go.mod
@@ -4,6 +4,7 @@ go 1.13
 
 require (
        github.com/aws/aws-sdk-go v1.20.21
-       github.com/cenkalti/backoff/v3 v3.1.1
+       github.com/cenkalti/backoff/v3 v3.2.2
+       github.com/cenkalti/backoff/v4 v4.0.0
        github.com/sergi/go-diff v1.0.0
 )
```

**Comment by andresvia** [comment]
@lmaitresym thanks for the report.

It seems like the `go get` command is affected by: ~https://github.com/golang/go/issues/29415~ (not really)

Try `GO111MODULE=on go get -v -u github.com/Autodesk/go-awsecs`

I'll be working in a more long term solution.

**Comment by andresvia** [comment]
@lmaitresym I tested with docker that go get now works, `GO111MODULE=on` not required. I had to freeze into backoff v3 until I have the time to evaluate v4. (created #14 for that)

Tested with:

`docker run golang:1.13 go get -v -u github.com/Autodesk/go-awsecs`

Thanks!
