### ISSUE TITLE
For loops that never loop - confusing code

### ISSUE THREAD

**Issue by TomMD** [andresvia/go-awsecs#18]
I'm looking here:

https://github.com/Autodesk/go-awsecs/blob/e94589a25b222b6e6999a60c9b22d8d0a24f952d/asg.go#L180

And while [playing with staticcheck](https://console.muse.dev/result/TomMD/go-awsecs/01EMPTT7GEYC8CA8NK5B6JWDPT) (a go Analyzer) I see this and another loop are ... non loops.  Is there an idiom here I'm missing that makes this style sensible?

**Comment by andresvia** [comment]
Thanks.

`ECSAPI.DescribeContainerInstances` accepts  an array of container instance IDs and returns another array of container instances descriptions, this call is passing an array with just one element.

https://github.com/Autodesk/go-awsecs/blob/e94589a25b222b6e6999a60c9b22d8d0a24f952d/asg.go#L166

https://github.com/Autodesk/go-awsecs/blob/e94589a25b222b6e6999a60c9b22d8d0a24f952d/asg.go#L168

The response from AWS *should* also contain 1 element.

This can be more explicit.

I've added #19 too.

**Comment by andresvia** [comment]
I got muse.dev installed by the org admin and run against a new branch I created:

https://github.com/Autodesk/go-awsecs/pull/21

https://console.muse.dev/result/Autodesk/go-awsecs/01EN1N912T0JXKZMXN0M1D3VG5?tab=results

The reported issues are now cleared.

I'm adding `staticcheck` to the regular checks in `CONTRIBUTING.md` as well as to Travis, and I guess muse.dev will now run the checks all the time? Which is good, is there any kind of un-protected badge that I can show in the `README.MD`?

**Comment by TomMD** [comment]
> I'm adding staticcheck to the regular checks in CONTRIBUTING.md as well as to Travis, and I guess muse.dev will now run the checks all the time?

Yes, Muse.dev will run on the checks all the time (on PRs) for every repo on which it's installed.  The status bar links to the console which has all the historic bugs, but the main interface is the PR.  In the PR you are getting comments on new bugs thought to be introduced (or at least exposed) by the current PR.

>  Which is good, is there any kind of un-protected badge that I can show in the README.MD?

Thank you for asking.  We don't have a badge at this time but have recorded the feature request.  Reach out any time if you have thoughts on analyzers, interface, or anything doesn't seem right.
