### ISSUE TITLE
Add a GitHub action for staticcheck

### ISSUE THREAD

**Issue by andresvia** [andresvia/go-awsecs#19]
Add a GitHub action for staticcheck to catch early issues like #18 

Could also be added to Travis.

**Comment by TomMD** [comment]
Following the conversation here from #18.

If you'd like the staticcheck and semgrep results posted as comments then the tool linked in #18 can be installed from https://github.com/apps/muse-dev.  Growing the tool set used by Muse is on par with adding to github actions (taking perhaps dozens of lines of script to add a new tool), with some differences that Muse has issue accumulation, filtering, and reports via the comment system along with providing a curated and managed default tool set.

Regarding this repository and golang - I previously looked at gosec but its results were duplicative of staticcheck, so you might want to choose just one of the two.  There's are other very opinionated tools out there, like goparamcount, which might be interesting depending on how your concerns align with those tools' opinions.

**Comment by andresvia** [comment]
Thanks I will try muse-dev but may need to convince the org admins, `goparamcount` is interesting.

```
goparamcount ./...
goparamcount: $GOPATH/github.com/Autodesk/go-awsecs/asg.go:111 - 5 parameters in function 'detachAndDrain' is too many
goparamcount: $GOPATH/github.com/Autodesk/go-awsecs/asg.go:210 - 6 parameters in function 'drainAll' is too many
goparamcount: $GOPATH/github.com/Autodesk/go-awsecs/asg.go:241 - 6 parameters in function 'enforceLaunchConfig' is too many
goparamcount: $GOPATH/github.com/Autodesk/go-awsecs/ecs-alter-service.go:22 - 12 parameters in function 'alterServiceOrValidatedRollBack' is too many
goparamcount: $GOPATH/github.com/Autodesk/go-awsecs/ecs.go:150 - 8 parameters in function 'copyTaskDef' is too many
goparamcount: $GOPATH/github.com/Autodesk/go-awsecs/ecs.go:174 - 11 parameters in function 'alterService' is too many
goparamcount: $GOPATH/github.com/Autodesk/go-awsecs/ecs.go:195 - 7 parameters in function 'findAndUpdateService' is too many
goparamcount: $GOPATH/github.com/Autodesk/go-awsecs/ecs.go:208 - 8 parameters in function 'updateService' is too many
goparamcount: $GOPATH/github.com/Autodesk/go-awsecs/ecs.go:284 - 12 parameters in function 'alterServiceValidateDeployment' is too many
d3fd9e9 (HEAD -> v1.4-rc, origin/v1.4-rc) Unmangling. Working on #18 and #19
```
